[theme]
background = "#00000000"
primary = "#000000"
secondary = "#000000"
title = "#000000"
playing = "#ff8000"
playing_selected = "light green"
playing_bg = "#804000"
highlight = "#ffffff"
highlight_bg = "#000000"
error = "light white"
error_bg = "red"
statusbar = "#000000"
statusbar_progress = "#ff8000"
statusbar_bg = "#ffffff"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
